// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HashtagController from "./hashtag_controller"
application.register("hashtag", HashtagController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TweetCardController from "./tweet_card_controller"
application.register("tweet-card", TweetCardController)

import TweetFormController from "./tweet_form_controller"
application.register("tweet-form", TweetFormController)
